DARPA-ASKEM/askem-beaker

Dockerfile
This installation is a bit hacky as it requires cloning the Mira repo and installing from source. I was not able to install it per the README but this seems to work. 
Verified by:
1. run `make build`
2. run the container (it spins up Jupyter)
3. exec into the container
4. open Python repl
5. run....
```
import sympy
import itertools
from mira.metamodel import *
from mira.modeling import Model
from mira.modeling.askenet.petrinet import AskeNetPetriNetModel
from mira.modeling.viz import GraphicalModel
```
to confirm imports work
=> Updates container to install Mira from source

docker-bake.hcl
Now that we do not need two identical images.
=> task: remove `jupyter-llm` image

environments/julia/install.jl
Added `Pkg.instantiate()` to `install.jl`. After this fix, `install.jl` and then sysimage worked as expected.
=> Minor fix to install.jl

Dockerfile, Makefile, pyproject.toml, src/askem_beaker/contexts/decapodes/agent.py, src/askem_beaker/contexts/oceananigans/agent.py
This PR upgrades the version of `askem-julia` being used to 5.0.0. `using` statements will be a bit slower because we got rid of the sysimage but it should only take a max of 5 seconds for Decapodes and Oceananigans (which sometimes took over a minute or two to load without sysimage in previous versions). This will break the current Decapodes context which was severely out of date anyway. Fixes to contexts will be applied as needed.
Running a Decapodes example in an `askem-beaker` notebook
=> Use `askem-julia` 5.0.0

src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_controlled_conversion_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_controlled_degradation_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_controlled_production_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_natural_conversion_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_natural_degradation_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_natural_production_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_observable.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/setup.py
Expressions were failing when a S was provided in the expression. This is because its predefined as a SingletonRegistry
Using clash here will override this SingletonRegistry
```
def add_observable(model, new_id: str, new_name: str, new_expression: str):
"""Add a new observable object to the template model
Parameters
----------
model : JSON
The model as an AMR JSON
new_id :
The ID of the new observable to add
new_name :
The display name of the new observable to add
new_expression :
The expression of the new observable to add as a MathML XML string
Returns
-------
: JSON
The updated model as an AMR JSON
"""
assert isinstance(model, TemplateModel)
tm = model
rate_law_sympy = sympy.parsing.sympy_parser.parse_expr(new_expression)
new_observable = Observable(name=new_id, display_name=new_name, …
```
=> Mira Model Edit expression hardening

src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_controlled_conversion_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_controlled_degradation_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_controlled_production_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_natural_conversion_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_natural_degradation_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_natural_production_template.py
When a user asks for a parameter that exists, do not create a new parameter but instead use the parameter in the model that exists.
There are probably cleaner approaches to this but a working solution is okay for now i think
Sample using a basic SIR with parameter: 
`"name='beta' display_name='β' description='infection rate' identifiers={} context={} units=None value=2.7e-07 distribution=Distribution(type='Uniform1', parameters={'minimum': 2.6e-07, 'maximum': 2.8e-07})"`
Question:
`Add a new transition from S to R with the name vaccine with the rate of beta.`
Result:
```
concepts_name_map = model.get_concepts_name_map()
if "S" not in concepts_name_map:
subject_concept = Concept(name = "S")
else:
subject_concept = concepts_name_map.get("S")
if "R" not in concepts_name_map:
outcome_concept …
```
=> Mira model Edit check for existing

src/askem_beaker/contexts/mira_config_edit/context.py, src/askem_beaker/contexts/mira_config_edit/procedures/python3/model_preview.py, src/askem_beaker/contexts/mira_model/context.py, src/askem_beaker/contexts/mira_model/procedures/python3/model_preview.py
Simple PR to add the post execution hook with the `model` response (not the full configuration wrapper) in the `mira_config_edit` context.
This also ensure support for previews of regnet + stock and flow on both the `mira_config_edit` context as well as the `mira_model` context.
=> Add post execution hook with preview

src/askem_beaker/contexts/dataset/context.py
If a user is saving a modified dataset there is a likelyhood that columns and/or data have changed, so the HMI-Server needs a clue that the columns information should be reset.
=> Clear dataset columns when creating a new dataset

Dockerfile, pyproject.toml
This PR adds Cartopy to the environment so it can be used for visualization and also bumps the `askem-julia` version to `7.0.1` (@fivegrant I know that's also covered in your `optimize` PR but figured I can add it here as well otherwise the build fails for me)
In this screenshot you can see that Cartopy was installed successfully.
=> Add cartopy to pyproject and bump askem-julia version in docker

src/askem_beaker/contexts/pyciemss/context.py
Using the `get_optimize`, the standalone Dev UI can now fully utilize the PyCIEMSS context again
=> Render `optimize` for Dev UI again

src/askem_beaker/contexts/mimi/agent.py, src/askem_beaker/contexts/mimi/context.py, src/askem_beaker/contexts/mimi/procedures/julia/model_info.jl, src/askem_beaker/contexts/mimi/procedures/julia/search_packages.jl
This PR adds two features:
- Reliable Plot templating (to help with the lack of `Mimi.explore`)
- Package registry search so `Pkg.add` suggestions are possible
Example of easy plotting:
Example of Package Registry search:
=> Add registry searching and plotting

src/askem_beaker/contexts/pyciemss/context.py, src/askem_beaker/contexts/pyciemss/procedures/python3/setup.py, src/askem_beaker/contexts/pyciemss/procedures/python3/simulate.py
This PR adds two new actions:
- `save_results_to_hmi`: This saves the content of the dictionary stored in `result` variable. This should work for any operation since it uses similar output-handling code from `pyciemss-service`
- `get_simulate`: Hydrates a `simulate` template just like `get_optimize` does 
While the simulation object saves to the HMI, it's not attached to a project. Modifying the tool to require a project_id shouldn't be too hard, however, there's a more difficult issue for making the result appear in the project. Simulation objects don't exist in the lefthand asset list and the simulation isn't attached to an operator. There will likely have to be some kind of UI change to accommodate this.
=> Save simulation object directly to HMI + Template simulate

docs/contexts_mira.md, docs/contexts_mira_model.md, src/askem_beaker/contexts/mira/context.py, src/askem_beaker/contexts/mira/procedures/python3/load_mira_model.py, src/askem_beaker/contexts/mira_model/context.py
Adds `project_id` to the `save_amr` (mira context) and `save_amr_request` (mira_model context) messages which will handle the specified save directly into the project. Also adds `save_amr` to mira context and documents the new message and expected arguments.
=> mira and mira_model contexts: save_amr message 

Dockerfile
pyciemss is pinned to a specific version of MIRA,  though it doesn't look like it uses anything version specific, so we should be able to install the latest version of MIRA on top of it.
=> flip implicit mira installation order so we can use latest

src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_controlled_conversion_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_controlled_degradation_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_controlled_production_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_natural_conversion_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_natural_degradation_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_natural_production_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_observable.py
Ben suggested we move to his parser as its a wrapper that adds a bit of safety around things such as "lamda"
=> move to MIRA's safe parse

src/askem_beaker/contexts/mira_model_edit/agent.py, src/askem_beaker/contexts/mira_model_edit/context.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/stratify.py
Add a stratify `procedure` and `tool` to the mira_model_edit context so this can be used rather than the `mira_model`'s version of this.
=> Moving stratify procedure to model edit

src/askem_beaker/contexts/mira_config_edit/agent.py, src/askem_beaker/contexts/mira_config_edit/context.py
Resolves https://github.com/DARPA-ASKEM/terarium/issues/3785#event-13102697406 
The issue arose when the user asks an agent to update a parameter that doesn't exist. Instead of notifying the user of the issue, Beaker threw an error.
This PR addresses this by comparing the parameter names supplied by the user against the parameter names in the model before generating the correct parameter update code. If one or more of the parameters that the user supplied do not exist in the model the agent notifies the user. 
> **Side Note**: since this loads the model into the Agent's context (not just the user space) we could answer questions about the current parameter/initial condition values without running code...if we wanted to make that update later.
=> Add handler to detect incorrect parameter name

src/askem_beaker/contexts/mira_config_edit/context.py, src/askem_beaker/contexts/pyciemss/context.py
We are currently in the midst of a major refactor on model-configurations and are changing how the endpoints will work. As this system gets integrated we've kept the old model config objects and endpoints active until we're ready to flip the switch.
Note that this PR should not be merged until HMI-Server is updated to use these endpoints correctly: https://github.com/DARPA-ASKEM/terarium/pull/3802
=> Point to the legacy endpoint for model configs, for now.

Dockerfile
Required for some mira code such as importing mira.dkg.web_client
Which is being used for model comparison
https://github.com/DARPA-ASKEM/askem-beaker/blob/653008a8a4e5791a55ee04fd934a7987c2673149/src/askem_beaker/contexts/mira/procedures/python3/compare_mira_models.py#L4
**Testing:**
Open container:
python:
`import mira.dkg.web_client`
prior to update this will fail with an error missing gilda
After this update will be fine
=> Fix: adding gilda dependency for mira

src/askem_beaker/contexts/mira_model_edit/agent.py
For model-edit:
Pascale wants to alter a rate_law that contains a parameter that does not exist, to do this we must first create the parameter so it will have an entry in the symbols table that is then subsequently needed for changing rate_law in the MMT.
Starting with the add parameter prompt, we added additional blurb about the rate_laws, as well as describing how to serialize a distribution object with a couple of common types: Uniform and Gaussian. The distribution part will probably need to be retro-fitted back into the "add_parameter" parts.
Start with an SIR with an "inf" transition, then a prompt like this may work: 
`Change rate law of inf to S * I * z., where z is a new parameter with uniform distribution of low=123 and high=456`
Check the source generated, should be able to …
=> add new tool to handle both changing expression and adding parameter at the same time

docs/contexts_model_configuration.md, src/askem_beaker/contexts/dataset/procedures/python3/setup.py
Addresses https://github.com/DARPA-ASKEM/terarium/issues/4523
(and adds an update to `model_configuration` context documentation I missed previously).
Tested with dataset `460a1e28-bfe8-434a-bf08-d64e90ac113c` which was the problematic one in Terarium due to its large number of rows.
=> Fix for dataset ellipsis

Dockerfile.light
A robot.jar  (https://github.com/ontodev/robot) is lazily downloaded when the script is run, this seems to create some weirdness because stderr is streamed back through the jupyter messages and seeming ended up as an error. To avoid this we will just download it ahead of time.
- Delete askem-beaker image and rebuild with "make dev"
- Once up, in Terarium do a model-comparison operator and check we get a comparison diagram on the first run
=> add robot.jar bootstrap

src/askem_beaker/contexts/mira_model_edit/agent.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/inspect_template_model.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/remove_templates.py
This PR adds three capabilities:
1. `inspect_template_model` tool that allows the agent to run code (behind the scenes) that gives it visibility to the structure of the template model. This can be used to answer questions like: "What are the templates whose subjects end in `diff`?"
2. `generate_code` tool that allows the agent to generate code for doing arbitrary things in response to: "Generate code to produce a list of the templates that end `diff`"
3. `remove_template` -> `remove_templates`: now this takes a `list` of template names to remove which allows users to ask things like "Remove templates from the model if the template subject name beings with `unvaccinated` or ends with `two` or `diff`"
Previously the agent had no ability to inspect the model which is now resolved ✅ . The …
=> Allow agent to inspect model and remove multiple templates

src/askem_beaker/contexts/dataset/context.py
"description" may not exist if the dataset are derived from TA3 operations. This PR adds a check guard.
Fixes: https://github.com/DARPA-ASKEM/terarium/issues/4890
In terarium with this beaker-instance:
- run simulation
- connect simulation result to dataset transform
- save data frame as a new dataset
=> check dataset description key exist

src/askem_beaker/contexts/mira/agent.py
This PR adds a new output to the return from Beaker for model comparison. In addition to the code that is generated, the JSON response will include `plot_order` which gives you the order in which the comparison plots will be generated.
For example, for `models = ['sir_model', 'SEIRHD_model', 'SEIRHD_model_export']` the response will be:
```
"plot_order": [["sir_model", "SEIRHD_model"], ["sir_model", "SEIRHD_model_export"], ["SEIRHD_model", "SEIRHD_model_export"]]
```
=> Add plot order to return from model comparison tool

src/askem_beaker/contexts/mira/agent.py, src/askem_beaker/contexts/mira/context.py, src/askem_beaker/contexts/mira/procedures/python3/compare_mira_models.py
This PR ensures that the code used to generate the comparison images also returns an array of comparison pairs in the proper order. It also add action for fetching comparison pairs called `get_comparison_pairs`. Either can be used to get the pairs of models being compared in each visualization: both return a list of lists of pairs.
For example, if the comparison is `model a`, `model b`, and `model c` then the pairs will be shown as:
```
[['model a', 'model b'], ['model a', 'model c'], ['model b', 'model c']]
```
and the first plot will be for `model a` and `model b`, the 2nd for `model a` and `model c` and so on.
=> Return comparison pairs from comparison code running

pyproject.toml
[The Beaker update to 1.7.0](https://github.com/jataware/beaker-kernel/pull/82) which is a major change might break things up. So let's pin it for now.
https://unchartedsoftware.slack.com/archives/C049E6PA16V/p1729521849998009
=> pin beaker-kernel to 1.6.8

src/askem_beaker/contexts/dataset/agent.py, src/askem_beaker/contexts/dataset/incidence_to_prevalence.md
This PR addresses the need to convert incidence data to prevalence data. This is accomplished by injecting a set of instructions, defined in `incidence_to_prevalence.md` to the agent as part of the `generate_code` tool. I think this is preferable to hardcoding a templated procedure since it will be _*much*_ more flexible in terms of its ability to handle datasets without super standardized formats and/or novel model compartments. 
The downside to this is that it increases the overall amount of information in the agent's context so therefore increases cost slightly. More importantly though, we don't really know how this new information in the agent's context might impact its decision making / code output for other tasks. This isn't easy to test, but based on my general assessment I think …
=> Provide agent instruction set on converting incidence to prevalence data

Dockerfile.light, src/askem_beaker/contexts/mira_model_edit/agent.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_observable_pattern.py
This PR adds a tool to the `mira-model-edit` context for adding observables via a pattern. For a model stratified by `Age` into `[children, adults, elderly]`, and vax status `[vaccinated, unvaccinated]` the user can specify something like:
> *"Can you add an observable called susceptible_vaccinated_children for the susceptible identifier and for vaccinated children?"*
The Agent will then:
1. Inspect the model state to ensure it knows the identifiers for the compartments/strata
2. Generate the appropriate code for adding the observable
This was tested by taking an [example SEIRHD model](https://github.com/liunelson/mira/blob/nliu/experiment/notebooks/nliu/data/example_models/seirhd_dist_params.json), stratifying by age and vax status and asking for various permutations of observable …
=> Add support for adding observables via pattern

src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_controlled_conversion_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_controlled_degradation_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_controlled_production_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_natural_conversion_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_natural_degradation_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_natural_production_template.py
* Removed parameter unit to avoid MIRA error when `""` is given as parameter unit
* Removed `initials` definition when the concept exists already (assuming existing concepts have initials already)
=> Improve the MIRA Edit Model procedures

src/askem_beaker/contexts/mira_model_edit/agent.py, src/askem_beaker/contexts/mira_model_edit/context.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_group_controlled_conversion_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_group_controlled_degradation_template.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_group_controlled_production_template.py
Linked to: https://github.com/DARPA-ASKEM/terarium/pull/6193
Set up:
- Update local vite config to port 8888
- Build and run beaker
Test:
- Ask the 3 sample questions
- See correct result code for each 
Group-controlled production
`Add a new transition that represents the states "Infected", "Hospitalized" controlling the production of the state "WastewaterViralLoad" with rate law "shed_rate * (Infected + Hospitalized)"`
Group-controlled degradation
`Add a new transition that represents the states "Susceptible", "Infected", "Recovered" controlling the degradation of the state "Hospitalized" with rate law "rec_rate * Hospitalized / (Susceptible + Infected + Recovered)"`
Group-controlled conversion
`Add a new transition that represents the states "Infected", "Recovered" controlling the …
=> Add group controlled

src/askem_beaker/contexts/dataset/procedures/python3/df_save_as.py, src/askem_beaker/contexts/dataset/procedures/python3/hmi_create_csv_dataset.py
We want to keep the index column as this is a useful and helpful thing for the user to have when they do operations such as merging or filtering datasets with eachother.
We cannot (and should not) have this as a blank header or our hmiserver will complain about this.
fix is for the `hmi_create_csv_dataset` file.
I have duplicated this to the `df_save_as` though I do not see where this `df_save_as` is being used. 
https://github.com/user-attachments/assets/bcf94e1d-e647-4b7d-8622-5204d7c53154
=> Dataset Context: Correction to saving files

src/askem_beaker/contexts/mira_model_edit/agent.py, src/askem_beaker/contexts/mira_model_edit/context.py
`agent.py` and `context.py` had misspellings of "unused" ("unsued" etc.). Fix those. May have caused this tool to be unusable. 
Fixes issue #185
=> Fixed typos with remove_x_parameters

src/askem_beaker/contexts/mira_model_edit/agent.py, src/askem_beaker/contexts/mira_model_edit/context.py, src/askem_beaker/contexts/mira_model_edit/procedures/python3/stratify.py
Request from Nelson to introduce proxy factored parameters when performing stratification. For example, if we stratify by age groups young/old and the parameter beta is included, we would get
- beta_young, beta_old
With factored parameters, beta will not be stratified per se, but instead we will have
- beta * f_beta_young, beta * f_beta_old
Where the `f_beta_*` are the newly introduced factored parameters
=> factor parameter when doing stratification

src/askem_beaker/contexts/mira_model_edit/procedures/python3/stratify.py
=> Improve stratification factor option

src/askem_beaker/contexts/mira_model_edit/procedures/python3/stratify.py
new_params is only defined within the `if add_param_factor == True:`. This means when `if add_param_factor == False;` it is undefined and the reference of it at the end would break. 
```
for __, factor in new_params.items():
```
Define it as empty at the top to allow it to be later referenced safely.
=> Fix: Stratify code new_params definition

Dockerfile.light
Fix to deal with the fact that `pyobo` is in flux and might not get a release on `pypi` for a while
=> Install pyobo from github since pypi version is out of date and broken
