Makefile
README.md
dev.py
dev_ui/src/index.ts
env.example
jupyter_kernel_proxy.py
llmkernel/kernel.json
llmkernel/kernel.py
main.py
poetry.lock
pyproject.toml
toolsets/dataset_toolset.py
toolsets/mira_model_toolset.py

Instead of running all of the code in a single IPython kernel with a kernel environment and a "shell" environment, this switches to using the kernel proxy to allow using alternate languages and kernels. Hope to soon add Julia and R as subkernels.
Now that functionality is back, planning to do further structural refactoring to make code maintenance, etc easier.

Refactor: kernel proxy overhaul

---

contexts/toolsets/mira_model_toolset.py

Seems like the header were incorrect set to parent_header instead of header

fix: set parent header for model-preview

---

src/askem_beaker/contexts/mira_model_edit/context.py

filling in missing functions in mira_model_edit context, just copying from model_edit

Adding missing functions to mira_model_edit using model_edit

---

src/askem_beaker/contexts/mira_model_edit/context.py

Adding to mira_model_edit context pt 2

---

docs/contexts_mira_model_edit.md
src/askem_beaker/contexts/mira_model_edit/agent.py
src/askem_beaker/contexts/mira_model_edit/context.py

Sample questions used for testing:
Adding templates:
1) Natural Conversion: 
Add a new transition from S to R with the name vaccine with the rate of v.
Add a new transition from I to D. Name the transition unlucky and give it a rate of I*u
2) Controlled Conversion: 
Add a new transition from S to R with the name vaccine with the rate of v. v depends on S
Add a new transition from I to D. Name the transition unlucky that has a dependency on R. The rate is I*R*u
3) Natural Production: 
Add a new transition from the transition rec to S with a rate of f.
add a new transition (from nowhere) to S with a rate constant of f
4) Controlled Production: 
Add a new transition from the transition rec to S with a rate of f. f depends on R. 
add a new transition (from nowhere) to S with a rate constant …

adding agent tools for many procedures in mira model edit

---

src/askem_beaker/contexts/mira_model_edit/context.py
src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_controlled_conversion_template.py
src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_controlled_degradation_template.py
src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_controlled_production_template.py
src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_natural_conversion_template.py
src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_natural_degradation_template.py
src/askem_beaker/contexts/mira_model_edit/procedures/python3/add_natural_production_template.py

Mira_model_edit was using an old env variable.
Meant to include the procedure changes in a separate PR but its small so oh well
Essentially use an existing concept if it can be found when adding templates

replace DATA_SERVICE_URL with HMI_SERVER_URL in mira_model_edit

---

src/askem_beaker/contexts/dataset/context.py

Accomodate simulation data structure:
```
{
"id": "f8d28c40-aafd-4537-8bdc-3220492ef8ec",
"executionPayload": {
},
"resultFiles": [
"result.csv"
],
"type": "SIMULATION",
"status": "COMPLETE",
"completedTime": "2024-02-22T17:39:11.0",
"engine": "SCIML",
"updatedOn": "2024-02-22T17:39:11.389+00:00"
}
```

acknowledge that simulation and dataset have different structure

---

src/askem_beaker/contexts/mira/agent.py
src/askem_beaker/contexts/mira/procedures/python3/compare_mira_models.py

creates a beaker tool to appropriately handle model comparison in a way that doesn't require synthesizing new code and is much more reliable

mira tools: more accurate structural model comparison 

---

src/askem_beaker/contexts/mira_model_edit/procedures/python3/remove_template.py

comment out eliminate_unused_params in mira model edit context as it was deleting more than expected

mira model edit context minor update

---

Dockerfile

Added RLang requirements to support [MITRE eval](https://github.com/DARPA-ASKEM/program-milestones/blob/main/Forecasting%20Challenges/T2-cum-death-plots.R) scripts

Add CDC forecast hub R requirements

---

src/askem_beaker/contexts/climate_data_utility/context.py
src/askem_beaker/contexts/climate_data_utility/procedures/python3/hmi_create_dataset.py
src/askem_beaker/contexts/climate_data_utility/procedures/python3/hmi_dataset_download.py
src/askem_beaker/contexts/climate_data_utility/procedures/python3/hmi_dataset_put.py

Fixes handling Terarium auth for env vars in response to earlier merge for security fixes. Auth env is fetched at context level and templated in.

Fix climate-data-utility for the new security env var change

---

Dockerfile
src/askem_beaker/contexts/pyciemss/context.py
src/askem_beaker/contexts/pyciemss/default_payload.json
src/askem_beaker/contexts/pyciemss/procedures/python3/df_save_as.py
src/askem_beaker/contexts/pyciemss/procedures/python3/setup.py

This PR extends the `save_result_to_hmi` action to check for the existence of output data in the `result` dictionary. If true, a dataset is saved to the provided project_id
Additionally, the PyCIEMSS version is bumped to latest

Save resulting PyCIEMSS dataset to project

---

src/askem_beaker/contexts/mira_model_edit/context.py
src/askem_beaker/contexts/mira_model_edit/procedures/python3/stratify.py

minor corrections to stratify intercept

---

src/askem_beaker/contexts/mira_config_edit/context.py

Fixed an issue where mira_config_edit calls would not work

fix: model params

---

src/askem_beaker/contexts/dataset/context.py
src/askem_beaker/contexts/dataset/procedures/python3/hmi_create_csv_dataset.py
src/askem_beaker/contexts/pyciemss/context.py

Using correct endpoint for uploading CSV files into hmi-server.

4003 bug dataset created from transform dataset has no column info

---

src/askem_beaker/contexts/mira_model_edit/procedures/python3/replace_ratelaw.py
src/askem_beaker/contexts/mira_model_edit/procedures/python3/stratify.py

- Add parameter rename to stratify, always turn it on
- fix proxy function for setting rate law on mmt-template

rename parameters in stratify and other MIRA changes

---

Dockerfile.light

@Tom-Szendrey to test and update pyciemss

Lock mira and update pyciemss verions

---

Dockerfile.light

Seemed like some packages got shifted around in MIRA

MIRA extra install for structured model comparison

---

docker-compose-full.yml

removing sciml which does not seem to be used

removing sciml from beaker.

---

src/askem_beaker/contexts/mira_model_edit/agent.py

Update stratify agent to have examples for structure
Related https://github.com/DARPA-ASKEM/terarium/pull/5108

Update stratify agent to have examples for structure

---

pyproject.toml

archytas==1.18
Source: https://unchartedsoftware.slack.com/archives/C049E6PA16V/p1729609444148339?thread_ts=1729608564.273779&cid=C049E6PA16V

Add missing dependency

---

src/askem_beaker/contexts/mira_model_edit/context.py
src/askem_beaker/contexts/mira_model_edit/procedures/python3/stratify.py

Issue:
- All parameters are being stratified 
Testing:
- Add a model to the workflow
- Add a stratify model
- select a parameter to stratify
- only the select parameter should have a matrix

fix for stratify bug

---

src/askem_beaker/contexts/dataset/procedures/python3/setup.py

Addresses https://github.com/DARPA-ASKEM/terarium/issues/5895

Data transform suppress warnings

---

src/askem_beaker/contexts/mira_model_edit/agent.py

- During Marjolein's demo, she found that the agent does not know how to use the MIRA tool to define the cumulative sum of a given variable and had to go to a notebook outside Terarium.
- You _can_ compute a cumulative sum using the `ControlledProduction` template
- The problem was that the docstrings for all the tools are not contextualised and lack practical examples
- This is resolved.
- To-do: 
- Solves this task: https://github.com/DARPA-ASKEM/terarium/issues/5901

Improve the docstring that instruct the usage of different MIRA model edit operations

---

src/askem_beaker/contexts/dataset/context.py
src/askem_beaker/contexts/dataset/procedures/python3/df_save_as.py

details in : https://github.com/DARPA-ASKEM/terarium/issues/6231

no index on server call for save dataset

---

src/askem_beaker/contexts/mira_model_edit/agent.py
src/askem_beaker/contexts/mira_model_edit/context.py
src/askem_beaker/contexts/mira_model_edit/procedures/python3/remove_unused_parameters.py
src/askem_beaker/contexts/mira_model_edit/procedures/python3/substitute_parameter.py

Mira Model Edit add procedures to remove parameters
Related: https://github.com/DARPA-ASKEM/terarium/pull/6316

Mira Model Edit add procedures to remove parameters

---

src/askem_beaker/contexts/dataset/agent.py
src/askem_beaker/contexts/dataset/context.py
src/askem_beaker/contexts/dataset/epi_metrics.md

Adds support for WIS and ATE per @liunelson's [issue here](https://github.com/DARPA-ASKEM/terarium/issues/6067#issuecomment-2603388244). 
@liunelson I still need some datasets to test with but with some testing I've done on some synthetic data things seem to work reasonably well. This approach is pretty simple really, just adding information to the agent prompt/context based on your write up.

Data transformation support for epi metrics

---

Dockerfile.light

Works from @bgyori to improve MIRA speed 
* https://github.com/gyorilab/mira/pull/431

Update MIRA version
